// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr4qBtw8F5M8rtC29-tU4MmO1LNk488ic',
    appId: '1:1069672679124:web:457e13f2a3be8ee9f39d41',
    messagingSenderId: '1069672679124',
    projectId: 'registrationapp-a6d64',
    authDomain: 'registrationapp-a6d64.firebaseapp.com',
    storageBucket: 'registrationapp-a6d64.firebasestorage.app',
    measurementId: 'G-76ZNL62S5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF4tAVKRLzI-v1UCu93si3Z1RtX1b3sMk',
    appId: '1:1069672679124:android:e2ccc95a2c33674af39d41',
    messagingSenderId: '1069672679124',
    projectId: 'registrationapp-a6d64',
    storageBucket: 'registrationapp-a6d64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASg-sj_ncFSenboRGoYVKc7ypCKPETp0E',
    appId: '1:1069672679124:ios:5406b925cd0ff681f39d41',
    messagingSenderId: '1069672679124',
    projectId: 'registrationapp-a6d64',
    storageBucket: 'registrationapp-a6d64.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASg-sj_ncFSenboRGoYVKc7ypCKPETp0E',
    appId: '1:1069672679124:ios:5406b925cd0ff681f39d41',
    messagingSenderId: '1069672679124',
    projectId: 'registrationapp-a6d64',
    storageBucket: 'registrationapp-a6d64.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr4qBtw8F5M8rtC29-tU4MmO1LNk488ic',
    appId: '1:1069672679124:web:af2ec29a4bbd7344f39d41',
    messagingSenderId: '1069672679124',
    projectId: 'registrationapp-a6d64',
    authDomain: 'registrationapp-a6d64.firebaseapp.com',
    storageBucket: 'registrationapp-a6d64.firebasestorage.app',
    measurementId: 'G-DKHX8D1188',
  );
}
